### ISSUE TITLE
How can I execute the sample RDF queries from a python env using SPARQLWrapper (or anything else)

### ISSUE THREAD

**Issue by yazoo178** [HHS/meshrdf#180]
I'm having a difficult time trying to run the SPAQL query examples outside of the demo environment provided on the webpage.

I suspect the has something to do with RDFS inference? flag == True, as I am unable to select this option when running the queries in a python environment. 

![image](https://user-images.githubusercontent.com/7006037/141958397-198c4b8b-89b9-49b5-885c-b4e2165b8eaa.png)

The result set is empty in my case, but for the same online example the result set contains over 50 results.

**Comment by danizen** [comment]
Although rdflib does not support inference, inference is done on our end, and is requested through the "inference" parameter.  In this case, the sparqlwrapper package only uses rdflib for parsing the results. If you need inference, then after you instantiate your object, you can use the method `addCustomParameter` as follows:

```python
from SPARQLWrapper import SPARQLWrapper, JSON
q = """
... your query ...
"""

sparql = SPARQLWrapper('https://id.nlm.nih.gov/mesh/sparql')
sparql.addCustomParameter('inference', 'true')
sparql.setQuery(q)
results = sparql.query().results()
print(results)
```

PS - it will be helpful if in future you use Github embedded code blocks (as I do above), rather than embedding an image from a Jupyter Notebook.  If you still have trouble, I will need your query as text rather than an image to help :)

**Comment by danizen** [comment]
Given your thumbs up - I will close.
