### ISSUE TITLE
Is there any sample java code for how to use meshrdf SPARQL as a client?

### ISSUE THREAD

**Issue by danizen** [HHS/meshrdf#20]
Is there any sample Java library code to use with MeshRDF?

**Comment by danizen** [comment]
I will use the results from http://hhs.github.io/meshrdf/sample-queries.html

**Comment by Klortho** [comment]
No. It's a pretty wide-open question, it seems to me, because there are a lot of things you might be interested in doing.  [Apache Jena](https://jena.apache.org/) is a Java-based library that is very popular for manipulating linked data.  You might try starting there -- it's pretty well documented with lots of examples.
