### ISSUE TITLE
Endpoint access...

### ISSUE THREAD

**Issue by jimfhahn** [HHS/meshrdf#27]
Looking for any known limit on access to the endpoint? I have a research project to use this api 

url = 'http://id.nlm.nih.gov/mesh/servlet/query?query=' + urllib.parse.quote_plus(query) + '&format=XML&limit=10&offset=0&inference=true'

And would like to know if I could parse about 300k headings from via the url above?

**Comment by bushmanb** [comment]
Thank you for your interest in MeSH RDF.  We are investigating an answer to your question and will provide you with a response shortly.  We would be interested to know more about your research project. Any information you can provide would be helpful to us in further understanding the use cases for MeSH RDF.  Just so you are aware, we will be releasing a revised beta version of MeSH RDF in mid-June.  Information about the schema changes being implemented as part of the upcoming release are located at http://hhs.github.io/meshrdf/release-notes.html

**Comment by jimfhahn** [comment]
There is a set of 300,000 e-books in our Library which, as a research project, we are attaching open linked data to, we are using the Bibframe RDF model as our template for the record RDF files, but utilize Schema.org micro data for display in the HTML. 

Many of the e-books which we have do include MeSH subject headings, and I had hoped to ensure we could gather open linked data for the description. These are very beta, but here is an example of our search page ( http://sif.library.illinois.edu/bibframe/search.php?utf8=%E2%9C%93&q=eye&button= ), and a record ( http://sif.library.illinois.edu/bibframe/html/7277072.html ).

**Comment by butlerj** [comment]
There is a limit you are likely to encounter with the process you have described and a modification that can be made to avoid the limit.

In order to avoid overloading the SPARQL endpoint service for the beta release, NLM requires that users of the service send no more than 500 requests per minute per IP address. Requests that exceed this limit will not be serviced, and service to that IP address will not be restored until 30 seconds time has elapsed.

One way to avoid encountering this limit for the retrieval you describe is to set &limit=1000 to retrieve 1,000 headings at a time.  This will result in only 300 requests for the 300K headings.

**Comment by bushmanb** [comment]
I was checking the sample links you sent and noticed what appears to be an error in the record you referenced  (http://sif.library.illinois.edu/bibframe/html/7277072.html). In this record, you have links to LCSH and MeSH, however the link for Photons--diagnostic use refers back to the bibliographic description rather than resolve to a subject authority.  If you are intending to use MeSH to represent this concept, the correct URI is http://id.nlm.nih.gov/mesh/D017785Q000176.  MeSH RDF contains URIs for valid descriptor/qualifier pairs however these URIs do not have a label associated with them.  The label can be generated from the hasDescriptor and hasQualifier properties.

**Comment by jimfhahn** [comment]
Thanks for the heads up on the HTML link!
