### ISSUE TITLE
Usable as a webservice?

### ISSUE THREAD

**Issue by jrjohnson** [HHS/meshrdf#56]
We've been using MeSH terms for a long time with the [Ilios Project](https://github.com/ilios/ilios).  Our existing implementation loads the full XML spec into a database so we can search for terms against our internal REST API [Ilios mesh parser](https://github.com/ilios/mesh-parser).

This is a pretty tricky process and consumes a lot of resources on our end.  In particular we have trouble historically staying up to date with the dictionary.

meshrdf seems like the solution to all of our woes.  It think our ideal implementation would be to write a nice query wrapper in javascript which would allow our users to enter terms and we would send the formatted request to http://id.nlm.nih.gov/mesh/query?query= and then parse the results.

A couple of questions:
Is anyone else using meshrdf in this way?  
See any problems / restrictions that would prevent us going down this path?
How *beta* is the service?  I'm concerned mainly about discontinuation and outages.  We can cope with schema and API changes.

Thanks a lot, we're really excited to discover this service and really hope we can take full advantage of it soon!

**Comment by bushmanb** [comment]
Thank you very much for your interest in MeSH RDF.  We plan to support the beta version of MeSH RDF as we continue to evaluate usage and need, and as resources allow.  Your use of the service as an API is the general idea - the SPARQL endpoint, http://id.nlm.nih.gov/mesh/sparql, supports CORS.   Refer to our [SPARQL and URI requests]( http://hhs.github.io/meshrdf/sparql-and-uri-requests.html) for more information on the parameters accepted.   If you have many users coming from the same IP address (for instance through a NAT or SNAT), you may have to watch out because there is a potential 4xx error if too many calls are done in a short period from a single IP.    You should write your JavaScript to handle the error code gracefully.    Refer to our [Acceptable Use Policy](http://hhs.github.io/meshrdf/acceptable-use-policy.html) for guidelines on this.  We will provide ample notice of any system and/or data changes via GitHub and other appropriate communication methods.  Please keep us informed as to the results of your implementation as we are interested in learning about and documenting use-cases.

**Comment by danizen** [comment]
@jrjohnson, did the answer of @bushmanb satisfy your need for information?   I want to add that we treat this differently as a Pilot/Beta internally.   We have Nagios monitors on the service, but instead of the night-time support staff getting a beeper call, I get email and get it back up in the morning.   We haven't had a hiccup I'm aware of however, and are committed to keeping the service up.

**Comment by jrjohnson** [comment]
Yes.  100%.  We're going to move this way with Ilios early next year.
