### ISSUE TITLE
OWL Ontology File For The Semantic Web?

### ISSUE THREAD

**Issue by digiman999** [HHS/meshrdf#72]
Hi, 

   I'm building a website that gathers research onto pages, with a page per MeSH descriptor.  I may be wrong, but to make it globally semantic i.e have the contents appear on semantic web search engines, isn't an online MeSH OWL ontology needed.  At present there's a HTML page per descriptor and SPARQL endpoint, but how are developers meant to link to that in the RDF data ie via sameAs or resource='xxx'.  Surely we need something like <rdf:Descriptor rdf:about=mesh:#cancer>?   

  The SPARQL endpoint seems fine, but must adhere to common URIs used by others eg label instead of preferred Descriptor Term
# NLMLD

Regards

**Comment by danizen** [comment]
The terminology itself is available at https://id.nlm.nih.gov/mesh/vocabulary.ttl.    URIs such as http://id.nlm.nih.gov/mesh/vocab#allowableQualifier redirect to this vocabulary.   Is there a particular reason you need the vocabulary as OWL rather than TTL?

**Comment by rafael5** [comment]
Getting into OWL would enable complex automated inferencing between terms, and post-coordinated composition of terms.  However, this wold be *way*  over the heads of 99% of web programmers today.  All they want is to link and query information based on simpler taxonomies. 

What are the largest knowledge organizations  using for their metadata / model language? [Google, Yahoo, Microsoft, Yandex (Russia's largest search engine), National Library of Congress, etc.]. 

They are using SKOS  and JSON-LD.

+1 for putting MeSH in JSON-LD and into the mainstream,   JSON-friendly form of RDF.

**Comment by danizen** [comment]
Making the OWL file available as well is a small thing, and I will try to do that in the next release.

**Comment by akuckartz** [comment]
See also https://github.com/HHS/meshrdf/issues/12 regarding SKOS.

**Comment by danizen** [comment]
@akuckartz and @digman999, the ontology is in OWL v1. I'm more expert now, and I understand that our decision not to use SKOS may be a problem for users.  The issue there was that skos:broader and skos:narrower are transitive.   For us that is an issue, because the transitivity is not right for MeSH and would produce strange conclusions, such as that Glaucoma is part of a Face. 

However, we do now host the owl file at https://id.nlm.nih.gov/mesh/vocabulary.owl   I had thought the code to populate the ftp site would place it in ftp://ftp.nlm.nih.gov/online/mesh/rdf/, but I see I still need to do that.

**NOTE**: We are moving away from github issues, but also towards better management of this as a production resource.   I will leave this open for a bit for you to respond, but I soon need to close it to redirect people to our support site.

**Comment by rafael5** [comment]
Dan,

Could you provide a link to your (new) support site so we may continue our
(public) dialogue on HHS information resources?

Thank you for all your good work.

Rafael


*Rafael Richards MD MS*

**Comment by danizen** [comment]
@rafael5, that is coming shortly.   It will be in the README, the website, and in the technical documentation site.  Although our model is very different from [http://purl.bioontology.org/ontology/MESH/](http://purl.bioontology.org/ontology/MESH/), we are also working to get our ontology loaded into BioPortal.

**Comment by VladimirAlexiev** [comment]
@danizen skos:broader is not transitive, there is a separate prop skos:broaderTransitive.
Nonetheless, translating MESH to SKOS is non-trivial, there are good reasons that MESH distinguishes between Descriptors and Concepts

**Comment by danizen** [comment]
@VladimirAlexiev, another take away from your issue 119 is that github issues should remain open, and I have argued so to our Workgroup.  NLM has many other github repositories, i.e. https://github.com/ncbi/sra-tools, and a lot of work happens there.

I have argued instead that we should make sure that we can cause our enterprise CRM tools to integrate with github, and for instance with github notifications, treat repositories hosted on github as our own "web properties" so that they be measured.  This is tangentially related to how open-source work such as work on JMOL (now jsmol) and biopython should count towards tenure, but that doesn't affect me.

Issues will remain until we hash this out; and thank you for your feedback.

**Comment by VladimirAlexiev** [comment]
@danizen I don't know NLM's full audience, but for developers and sem.data experts, I am sure that NLM will get much better collaboration and richer feedback if you stick with Github.

**Comment by danizen** [comment]
This is fixed, by the way.   http://id.nlm.nih.gov/mesh/vocab redirects to https://id.nlm.nih.gov/mesh/vocabulary.owl, and the TTL remains available as well.

**Comment by VladimirAlexiev** [comment]
@danizen is the ontology served with content negotiation? Rdf, turtle, html

**Comment by danizen** [comment]
@VladimirAlexiev , sort-of /mesh/vocab will redirect to /mesh/vocabulary.owl, and vocabulary.ttl is also available.  I can add other redirects, and these can take the Accept request header into account to add an extension.   For the void graph, we make it available only as /mesh/void.ttl, but that could be changed.
