### ISSUE TITLE
MeSH  in JSON-LD /  schema.org compatible form

### ISSUE THREAD

**Issue by rafael5** [HHS/meshrdf#74]
Is there any technical reason MeSH could not be published in the JSON-LD form of RDF?  Can the MeSH model fit in JSON-LD without loss of functionality?

JSON-LD  is the form of RDF  the www  search engines use to crawl, index, structure, and  semantically search all the structured data on the web;  it is also a most approachable form of RDF for web programmers already familiar with JSON.

Links
- https://schema.org
- http://json-ld.org

**Comment by darobin** [comment]
For what it's worth we would find a JSON-LD version quite useful as well.

**Comment by davidanderson3** [comment]
Thanks for your questions. You can request JSON-LD for [any given URI](https://id.nlm.nih.gov/mesh/D015242.json-ld). You can also build a [CONSTRUCT query in our SPARQL endpoint](https://id.nlm.nih.gov/mesh/sparql?query=PREFIX%20mesh%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0D%0ACONSTRUCT%20%7B%20mesh%3AD015242%20%3Fp%20%3Fo%20.%20%7D%0D%0AFROM%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0D%0AWHERE%20%7B%0D%0A%20%20mesh%3AD015242%20%3Fp%20%3Fo%20.%0D%0A%7D%0D%0A&format=JSON-LD) that will return JSON-LD. 

We also produce an n-triples bulk download file available here: [ftp://ftp.nlm.nih.gov/online/mesh/](ftp://ftp.nlm.nih.gov/online/mesh/). I think there are scripts out there that can help with the transformation to JSON-LD. 

We have not mapped MeSH to schema.org classes and properties. Do you have a specific use case for this? 

Thanks again for your questions!

**Comment by rafael5** [comment]
The use case is for a MeSH-aware EHR that could generate precise, semantic queries to PubMed for certain types of information (problems, diagnoses, conditions, treatments, studies, outcomes), providing a PubMed-driven infobutton with targted medical literature on these fields / topics.

To know if this is a valid use case, perhaps a little knowledge about how Pubmed's search engine works would go a long way.  For example, would keywords enriched with MeSH headings provide better search results?

**Comment by rafael5** [comment]
Beyond schema.org using JSON-LD,   the VA is also moving to JSON-LD as its enterprse metadata and model standard.

https://github.com/vistadataproject/documents#technical-overview

So linkage to MeSH to the the VA's  1200 hospitals and clinics through VISTA is another use case...

**Comment by darobin** [comment]
From our end it is not so much the actual results in JSON-LD as having a JSON-LD context to import. We are [using MeSH](https://research.science.ai/article/memory-efficient-mesh-tagging) in an environment that is [very Web/JSON oriented](https://research.science.ai/article/web-first-data-citations). Having the context directly in JSON-LD is simpler in that it saves us from having to convert to that. (But I wouldn't rate it as urgent or anything.)

**Comment by danizen** [comment]
@rafael5, we are still in a Beta mode because of some stability issues we've had with Virtuoso.   However, you are right that there is really no "search engine" providing full-text search.   Once we work out the stability issues we've had with Virtuoso (expected soon, at last), then we will be able to decide what priority to place on future development.    You may also want to look at https://meshb.nlm.nih.gov/, which may have structured meta-data and is a full-text index (Elasticsearch).   I do not know whether it has an API however.

**Comment by danizen** [comment]
@rafael5, there seem to be 2 or 3 questions here.   Can you clarify what you are looking for?

* JSON-LD for results - this can be accomplished in quite a variety of ways, the easiest is to send a request header `Accept: application/rdf+json` to resolve URIs like https://id.nlm.nih.gov/mesh/D017563.   The MIME-type will soon change to `application/ld+json` for another issue.

* Possibly, a request for a full-text search engine.  "Interstitial Lung Diseases" cannot be matched easily against `rdfs:label`, because it is actually "Lung Diseases, Interstitial" and this would help make the SPARQL a bit easier.  Please file a separate request if that was what you had in mind when mentioning PubMed.

* https://schema.org support in the result pages.   This is a bit harder, it would be easier to support RDFa, but this also requires a change to our Data Model/vocabulary to move to SKOs from what I understand.

**Comment by danizen** [comment]
@rafael5 - I am corrected that https://schema.org does not require changes to the Data Model, and will be preferred over RDFa.   However, we still need to figure out which of these is/are the solution for your issue.

**Comment by danizen** [comment]
@rafael5 , we've captured this in an internal bug tracker, but we are closing Github issues and re-directing users to NLM customer support now that this is a production service.

**Comment by rafael5** [comment]
RafDan,

Could you provide a link to your (new) support site so we may continue our
(public) dialogue on HHS information resources?

Thank you for all your good work.

Rafael


*Rafael Richards MD MS*

**Comment by VladimirAlexiev** [comment]
@rafael5 schema.org has nothing to do with jsonld. 
- schema.org metadata can be delivered in any RDF serialization. They used to recommend microformats, but now recommend jsonld and turtle embedded in `<head><script>`
- jsonld can be used for any RDF data.

@danizen https://id.nlm.nih.gov/mesh/D017563.json-ld looks good. Most importantly, it's content identical to the other RDF formats:
```sh
curl -O https://id.nlm.nih.gov/mesh/D017563.json-ld
riot -out nt D017563.jsonld |sort > D017563.jsonld.nt
curl -O https://id.nlm.nih.gov/mesh/D017563.n3
riot -out nt D017563.n3 |sort > D017563.n3.nt
curl -O https://id.nlm.nih.gov/mesh/D017563.rdf
riot -out nt D017563.rdf |sort > D017563.rdf.nt
```
It can take just a bit of improvement:
- put the context to https://id.nlm.nih.gov/mesh/context.jsonld and refer to it by URL
- add http://id.nlm.nih.gov/mesh/vocab#active to context
- the recommended extension is `.jsonld` not `.json-ld`
- given that all your strings are in EN, set the "default language" (https://w3c.github.io/json-ld-syntax/#dfn-default-language, https://w3c.github.io/json-ld-syntax/#string-internationalization) so you could use a simple string instead of eg this:
```js
    "historyNote" : {
      "@language" : "en",
      "@value" : "94; was LUNG DISEASE, INTERSTITIAL see PULMONARY FIBROSIS ..."
    },
```
